name: metag_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools=2.30.0
  - blast=2.6.0
  - bwa=0.7.17
  - fastqc=0.11.9
  - kraken2=2.1.2
  - pip=21.2.2
  - python=3.6
  - pyyaml=5.4.1
  - samtools=1.4.1
  - seqtk=1.3
  - trimmomatic=0.39
  - yaml=0.2.5
  - pip:
    - multiqc==1.14
